apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: MACHINESET_NAME
  namespace: openshift-machine-api
spec:
  minReplicas: 0
  maxReplicas: 1000
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: MACHINESET_NAME
