ci_presets:
  # name of the presets to apply, or null if no preset
  name: null
  # list of names of the presets to apply, or a single name, or null if no preset
  names: null

  cleanup_on_exit:
    clusters.cleanup_on_exit: true

secrets:
  dir:
    name: psap-ods-secret
    env_key: PSAP_ODS_SECRET_PATH
  # name of the file containing the properties of LDAP secrets
  s3_ldap_password_file: s3_ldap.passwords
  brew_registry_redhat_io_token_file: brew.registry.redhat.io.token

clusters:
  cleanup_on_exit: true

rhods:
  catalog:
    image: brew.registry.redhat.io/rh-osbs/iib
    tag: 524781
    channel: beta
    version: 1.29.0
