---
gpu_burn_entrypoint: projects/gpu-operator/roles/gpu_operator_run_gpu_burn/files/entrypoint.sh
gpu_burn_pod: templates/gpu_burn_pod.yml
gpu_burn_src_dir: projects/gpu-operator/roles/gpu_operator_run_gpu_burn/files/gpu-burn
