---
- name: Ensure that a hostname was passed in parameter
  fail: msg="'benchmarking_deploy_coco_dataset_node_hostname' must be provided"
  when: benchmarking_deploy_coco_dataset_node_hostname | default('', true) | length == 0

- name: Ensure that a valid hostname name was passed in parameter
  command: oc get nodes -l kubernetes.io/hostname={{ benchmarking_deploy_coco_dataset_node_hostname }} -oname

- name: Delete the s3 secret, if it exists
  when: benchmarking_deploy_coco_dataset_s3_cred | default('', true) | length != 0
  command:
    oc delete secret/s3-secret
       -n {{ benchmarking_deploy_coco_dataset_namespace }}
       --ignore-not-found=true

- name: Create the s3 secret
  when: benchmarking_deploy_coco_dataset_s3_cred | default('', true) | length != 0
  command:
    oc create secret generic s3-secret
       -n {{ benchmarking_deploy_coco_dataset_namespace }}
       --from-file=cococred.csv={{ benchmarking_deploy_coco_dataset_s3_cred }}

- name: Create the entrypoint ConfigMap file
  shell:
    oc create cm coco-dataset-downloader
       --from-file="entrypoint.sh={{ coco_dataset_entrypoint }}"
       -n {{ benchmarking_deploy_coco_dataset_namespace }}
       --dry-run=client
       -oyaml
       > {{ artifact_extra_logs_dir }}/000_configmap_coco-dataset_entrypoint.yml

- name: Create the entrypoint ConfigMap resource
  command: oc apply -f {{ artifact_extra_logs_dir }}/000_configmap_coco-dataset_entrypoint.yml

- name: Apply the PVC template
  template:
    src: "{{ coco_dataset_pvc }}"
    dest: "{{ artifact_extra_logs_dir }}/001_pvc_coco-dataset.yml"
    mode: '0400'

- name: Check if the PVC already exists
  command: oc get -f "{{ artifact_extra_logs_dir }}/001_pvc_coco-dataset.yml" -oname
  failed_when: false
  register: has_pvc

- name: Create a PVC for storing the COCO dataset
  when: has_pvc.rc != 0
  command:
    oc apply -f "{{ artifact_extra_logs_dir }}/001_pvc_coco-dataset.yml"

- name: Apply the Pod template
  template:
    src: "{{ coco_dataset_pod }}"
    dest: "{{ artifact_extra_logs_dir }}/002_pod_coco-dataset.yml"
    mode: '0400'

- name: Delete the Pod, if it exists
  command:
    oc delete -f "{{ artifact_extra_logs_dir }}/002_pod_coco-dataset.yml"
       --ignore-not-found=true

- name: Create a Pod for downloading the COCO dataset
  command:
    oc apply -f "{{ artifact_extra_logs_dir }}/002_pod_coco-dataset.yml"

- name: Wait for the downloader Pod to terminate
  command:
    oc get -f "{{ artifact_extra_logs_dir }}/002_pod_coco-dataset.yml"
       --no-headers
       -ocustom-columns=phase:status.phase
  register: wait_dataset_downloader_pod
  until: "'Succeeded' in wait_dataset_downloader_pod.stdout or 'Failed' in wait_dataset_downloader_pod.stdout or 'Error' in wait_dataset_downloader_pod.stdout"
  retries: 100
  delay: 60

- name: Get the logs of the download Pod (debug)
  shell:
    oc logs pod/coco-dataset-downloader
       -n {{ benchmarking_deploy_coco_dataset_namespace }}
       > {{ artifact_extra_logs_dir }}/pod_downloader.log
  failed_when: false

- name: Get the description of the download Pod (debug)
  shell:
    oc describe pod/coco-dataset-downloader
       -n {{ benchmarking_deploy_coco_dataset_namespace }}
       > {{ artifact_extra_logs_dir }}/pod_downloader.desc
  failed_when: false

- name: Fail if the the downloader Pod failed
  when: "'Failed' in wait_dataset_downloader_pod.stdout or 'Error' in wait_dataset_downloader_pod.stdout"
  fail: msg="The download failed ..."
