---
- name: Check that cluster_deploy_redis_server_namespace is defined
  fail: msg="Bailing out. This role requires 'cluster_deploy_redis_server_namespace'"
  when: not cluster_deploy_redis_server_namespace

- name: Create redis namespace
  shell:
    set -o pipefail;
    oc create ns "{{ cluster_deploy_redis_server_namespace }}" -oyaml --dry-run=client | oc apply -f-

- name: Delete redis deployment, if it exists
  command:
    oc delete
       -f "{{ cluster_deploy_redis_server_deployment }}"
       --ignore-not-found
       -n "{{ cluster_deploy_redis_server_namespace }}"

- name: Create the redis deployment
  command:
    oc create
       -f "{{ cluster_deploy_redis_server_deployment }}"
       -n "{{ cluster_deploy_redis_server_namespace }}"

- name: Show and Save the host of the redis route
  shell: |
    hostname=redis.{{ cluster_deploy_redis_server_namespace }}.svc.cluster.local
    echo "$hostname"
    echo "$hostname" > "{{ artifact_extra_logs_dir }}/hostname"
