---
- name: Ensure that GRPCurl is available
  shell:
    which grpcurl

- name: Create the artifact directory
  file:
    path: "{{ artifact_extra_logs_dir }}/{{ kserve_validate_model_inference_service_name }}"
    state: directory
    mode: '0755'

- name: Get the name of the KSVC
  shell:
    set -o pipefail;
    oc get ksvc
       -lserving.kserve.io/inferenceservice={{ kserve_validate_model_inference_service_name }}
       -n {{ kserve_validate_model_namespace }}
       -ojsonpath='{.items[0].status.url}'
       | sed 's|https://||'
  register: ksvc_hostname_cmd

- name: Wait for the model to answer successfully
  shell: |
    set -o pipefail;
    i=0;

    GRPCURL_DATA=$(cat "{{ kserve_validate_model_dataset }}" | jq .dataset[$i].input )

    grpcurl \
        -insecure \
        -d "$GRPCURL_DATA" \
        -H "mm-model-id: {{ kserve_validate_model_model_id }}" \
        {{ ksvc_hostname_cmd.stdout }}:443 \
        caikit.runtime.Nlp.NlpService/TextGenerationTaskPredict

  register: grpcurl_working_cmd
  retries: 60
  delay: 5
  until: grpcurl_working_cmd.rc == 0

- name: Inform | Next task runs the load test
  debug: msg="Next task runs the validation test. It runs {{ kserve_validate_model_query_count }} queries. Artifacts will be saved into '{{ artifact_extra_logs_dir }}/{{ kserve_validate_model_inference_service_name }}'."


- name: Query the model endpoint
  shell: |
    set -o pipefail;
    set -e;
    dest={{ artifact_extra_logs_dir }}/{{ kserve_validate_model_inference_service_name }}/answers.json
    queries={{ artifact_extra_logs_dir }}/{{ kserve_validate_model_inference_service_name }}/questions.json
    rm -f "$dest" "$queries"

    for i in $(seq {{ kserve_validate_model_query_count }}); do
      GRPCURL_DATA=$(cat "{{ kserve_validate_model_dataset }}" | jq .dataset[$i].input )
      echo $GRPCURL_DATA >> "$queries"
      grpcurl \
        -insecure \
        -d "$GRPCURL_DATA" \
        -H "mm-model-id: {{ kserve_validate_model_model_id }}" \
        {{ ksvc_hostname_cmd.stdout }}:443 \
        caikit.runtime.Nlp.NlpService/TextGenerationTaskPredict \
        >> "$dest"
      echo "Call $i/{{ kserve_validate_model_query_count }} passed"
     done
  register: query_model_cmd
  until: query_model_cmd.rc == 0
  retries: 5
  delay: 30
