apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    opendatahub.io/username: "{{ notebook_name }}"
    openshift.io/description: "{{ notebook_name }} workbench"
    openshift.io/display-name: "{{ notebook_name }}"
    ci-artifacts/base-url: "/notebook/{{ notebook_name }}/{{ notebook_name }}"
  labels:
    app: "{{ notebook_name }}"
    ci-artifacts.single-notebook-perf: "true"
  name: "{{ notebook_name | truncate(35, true, '') }}"
spec:
  template:
    metadata:
      labels:
        app: "{{ notebook_name }}"
        ci-artifacts.single-notebook-perf: "true"
        opendatahub.io/dashboard: "true"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: nvidia.com/gpu.present
                operator: NotIn
                values:
                - "true"
            weight: 1
      containers:
      - env:
        - name: NOTEBOOK_FILES
          value: /mnt/notebook_files
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/{{ notebook_name }}/{{ notebook_name }}
                              --ServerApp.quit_button=False
        - name: JUPYTER_IMAGE
          value: {{ notebook_image_address }}

        # custom benchmark configuration
        - name: NOTEBOOK_FILENAME
          value: "{{ notebooks_benchmark_performance_notebook_filename }}"
        - name: BENCHMARK_NAME
          value: "{{ notebooks_benchmark_performance_benchmark_name }}"
        - name: BENCHMARK_REPEAT
          value: "{{ notebooks_benchmark_performance_benchmark_repeat }}"
        - name: BENCHMARK_NUMBER
          value: "{{ notebooks_benchmark_performance_benchmark_number }}"

        image: {{ notebook_image_address }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ notebook_name }}/{{ notebook_name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: main
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/{{ notebook_name }}/{{ notebook_name }}/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        volumeMounts:
        - mountPath: /mnt/notebook_files
          name: {{ notebook_file_cm_name }}
        workingDir: /opt/app-root/src
      volumes:
      - name: {{ notebook_file_cm_name }}
        configMap:
          name: {{ notebook_file_cm_name }}
